# Generated by Django 5.1.6 on 2025-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meuapp", "0002_remove_cliente_name_cliente_nome_completo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nome_completo",
            field=models.CharField( max_length=200),
        ),
    ]
