# Generated by Django 5.1.6 on 2025-03-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meuapp", "0003_alter_cliente_nome_completo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nome_completo",
            field=models.CharField(max_length=200),
        ),
    ]
