# Generated by Django 5.1.6 on 2025-03-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meuapp", "0005_alter_cliente_nome_completo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="nome_completo",
        ),
        migrations.AddField(
            model_name="cliente",
            name="primeiro_nome",
            field=models.CharField(default="pn_usuario{self.user.id}", max_length=200),
        ),
        migrations.AddField(
            model_name="cliente",
            name="sobre_nome",
            field=models.CharField(default="sn_usuario{self.user.id}", max_length=200),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                default="email_usuario{self.user.id", max_length=200
            ),
        ),
    ]
