# Generated by Django 5.1.6 on 2025-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meuapp", "0006_remove_cliente_nome_completo_cliente_primeiro_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                default="email_usuario{self.user.id}", max_length=200
            ),
        ),
    ]
