# Generated by Django 5.1.6 on 2025-03-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meuapp", "0007_alter_cliente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
    ]
